# Generated by Django 4.1.3 on 2022-11-22 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appr_nom', models.CharField(max_length=255)),
                ('appr_prenom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_title', models.CharField(max_length=255, null=True)),
                ('brief_url', models.CharField(max_length=255, null=True)),
                ('brief_nb_apprs', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_nom', models.CharField(max_length=255, null=True)),
                ('grp_apprs', models.ManyToManyField(to='app.appr')),
                ('grp_brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brief')),
            ],
        ),
    ]
